from enum import Enum


class AugmenterFields:
    DEFAULT_ROTATION_RANGE=10
    DEFAULT_FLIP_PROBABILITY=0.5
    DEFAULT_BRIGHTNESS_RANGE=0.1
    DEFAULT_CONTRAST_RANGE=0.1
    DEFAULT_DENOISE_PROBABILITY=0.3
    